
rvm:
  - 1.8.7 # (par défaut)
gemfile: gemfiles/Gemfile.ci
before_script: 
	- sed -e 's/password//' -e 's/0.0.0.0/127.0.0.1/' settings-sample.yml > settings.yml
	- sudo apt-get install libmp3lame-dev libfaad-dev libx264-dev faac ffmpeg
	- sudo wget -O /tmp/airvideo.test.server.jar http://inmethod.com/air-video/download/linux/alpha4/AirVideoServerLinux.jar 
	- sudo java -jar /tmp/airvideo.test.server.jar /tmp/test.properties > /dev/null &
